name: Deploy with Zerops

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: alpine-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with Zerops
        uses: nermalcat69/test-action@v0.0.6
        with:
          access-token: ${{ secrets.ZEROPS_TOKEN }}
          service-id: r83A9lP7TBiv4Axx2lsZFg
