name: Deploy with Zerops

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
      - name: Deploy with Zerops
        uses: nermalcat69/test-action@v0.0.4
        with:
          access-token: ${{ secrets.ZEROPS_ACCESS_TOKEN }}
