name: Deploy with Zerops

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Echo ZEROPS_TOKEN
        run: echo $ZEROPS_TOKEN
        env:
          ZEROPS_TOKEN: ${{ secrets.ZEROPS_TOKEN }}

      - name: Deploy with Zerops
        uses: nermalcat69/test-action@v0.0.6
        with:
          access-token: $ZEROPS_TOKEN
          service-id: r83A9lP7TBiv4Axx2lsZFg
        env:
          ZEROPS_TOKEN: ${{ secrets.ZEROPS_TOKEN }}
