name: Deploy with Zerops

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Echo ZEROPS_TOKEN
        run: echo ${{ secrets.ZEROPS_TOKEN }}

      - name: Deploy with Zerops
        uses: nermalcat69/test-action@v0.0.6
        with:
          access-token: ${{ secrets.ZEROPS_TOKEN }}
          service-id: r83A9lP7TBiv4Axx2lsZFg
